symfony:
    build: .
    dockerfile: Dockerfile-Symfony

    container_name: symfony
    links:
       - mysql
    ports:
       - "8000:80"
    volumes:
       - .:/var/app
mysql:
    image: mysql:5.6
    container_name: mysql
    environment:
       - MYSQL_ROOT_PASSWORD=pass